// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
	{
		name: "Member",
		checkConstraints: {
			member_xata_id_length_xata_id: {
				name: "member_xata_id_length_xata_id",
				columns: ["xata_id"],
				definition: "CHECK ((length(xata_id) < 256))",
			},
		},
		foreignKeys: {},
		primaryKey: [],
		uniqueConstraints: {
			_pgroll_new_member_xata_id_key: {
				name: "_pgroll_new_member_xata_id_key",
				columns: ["xata_id"],
			},
			member__pgroll_new_mail_key: {
				name: "member__pgroll_new_mail_key",
				columns: ["mail"],
			},
		},
		columns: [
			{
				name: "characters",
				type: "multiple",
				notNull: false,
				unique: false,
				defaultValue: null,
				comment: "",
			},
			{
				name: "isRestMember",
				type: "bool",
				notNull: false,
				unique: false,
				defaultValue: "false",
				comment: "",
			},
			{
				name: "jobs",
				type: "multiple",
				notNull: false,
				unique: false,
				defaultValue: null,
				comment: "",
			},
			{
				name: "mail",
				type: "text",
				notNull: true,
				unique: true,
				defaultValue: null,
				comment: "",
			},
			{
				name: "sub_jobs",
				type: "multiple",
				notNull: false,
				unique: false,
				defaultValue: null,
				comment: "",
			},
			{
				name: "user_name",
				type: "text",
				notNull: false,
				unique: false,
				defaultValue: null,
				comment: "",
			},
			{
				name: "xata_createdat",
				type: "datetime",
				notNull: true,
				unique: false,
				defaultValue: "now()",
				comment: "",
			},
			{
				name: "xata_id",
				type: "text",
				notNull: true,
				unique: true,
				defaultValue: "('rec_'::text || (xata_private.xid())::text)",
				comment: "",
			},
			{
				name: "xata_updatedat",
				type: "datetime",
				notNull: true,
				unique: false,
				defaultValue: "now()",
				comment: "",
			},
			{
				name: "xata_version",
				type: "int",
				notNull: true,
				unique: false,
				defaultValue: "0",
				comment: "",
			},
		],
	},
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
	branch: process.env.XATA_BRANCH,
	apiKey: process.env.XATA_API_KEY,
	databaseURL:
		"https://Boardgame-Podcast-s-workspace-39js0q.us-west-2.xata.sh/db/ff14-guild",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
	constructor(options) {
		super({ ...defaultOptions, ...options }, tables);
	}
}
let instance;
/** @type { () => XataClient } */
export const getXataClient = () => {
	if (instance) return instance;
	instance = new XataClient();
	return instance;
};
